### ISSUE TITLE
Cannot find the ressdata directory

### ISSUE THREAD

**Issue by WongResearch** [zdenop/qt-box-editor#28]
Hi 

I can't seem to get gt-box-editor to read tessdata folder.

I select the path to C:\Program Files\Tesseract-OCR\tessdata  

I have the version I have installed is 3.01-1 
tesseract-ocr-setup-3.01-1.exe

Thanks in advance.

**Comment by nkrishnankrishna** [comment]
HI Zdenop,
  Iam install in my Pc operator system using Windows 10  Qt-box-editor v 1.12rc1 When open Tif its not display left hand side window text letter  x-axis and y-axis.
can you send the screen shots how to create trained data file in Windows 10 screen shots.
Thanks and appreciate
