### ISSUE TITLE
Building this tool

### ISSUE THREAD

**Issue by smac89** [zdenop/qt-box-editor#48]
How do I build and use this? I am using Ubuntu and I have installed both tesseract and compiled/installed leptonica. In the INSTALL file it says: "adjust location of leptonica and tesseract in qt-box-editor.pro", what does that mean? I have looked through the file mentioned and I'm not sure where to put the libraries mentioned.

When I run make in the folder, I get this error:
```In file included from src/ChildWidget.cpp:33:0:
src/TessTools.h:26:31: fatal error: tesseract/baseapi.h: No such file or directory```

Please help

**Comment by zdenop** [comment]
how did you installed tesseract? From source?

**Comment by smac89** [comment]
I installed it from the terminal by doing

sudo apt-get install tesseract libtesseract3 libleptonica

**Comment by zdenop** [comment]
you need to install "devel" packages of tesseract and leptonica

**Comment by smac89** [comment]
That solved it, thanks
