### ISSUE TITLE
Multiple dialogs on reload file v1.12-dev

### ISSUE THREAD

**Issue by smac89** [zdenop/qt-box-editor#49]
Steps to reproduce:
- load a box file into the editor
- modify the box file outside the editor
- dialog**s** pops up to reload
- **Now have to close them all or force close**

**Comment by zdenop** [comment]
Please provide more information: What OS are you using? What version of Qt?

**Comment by smac89** [comment]
At the time I was using Ubuntu 15.04 and I think Qt 4.5. I mostly work on windows now so I haven't had time to  test again. I will see if I can build on windows and see if the problem is still there

**Comment by zdenop** [comment]
Seems like using Qt5 can help see issue #57
