### ISSUE TITLE
invalid box files 

### ISSUE THREAD

**Issue by fafo** [zdenop/qt-box-editor#50]
In saved box files the space char is missing; all box files containing a space are saved as
space left space bottom space right  space stop
instead of 
space space left space bottom space right  space stop

**Comment by zdenop** [comment]
space is delimiter. 
IMO it is noses to ask tesseract train contour from space...

**Comment by fafo** [comment]
Well, I noticed just because  text2image creates training boxfiles *with boxes for spaces* and sometimes they need to be corrected... Yep, it's dumb, but useful for automatic training
