### ISSUE TITLE
Cannot run on Windows 8

### ISSUE THREAD

**Issue by bliet** [zdenop/qt-box-editor#51]
When I run the exe (in the same folder like the dependecies) I get a Runtime Error.
![runtimeerror](https://cloud.githubusercontent.com/assets/3314090/11558472/4f06169c-99b3-11e5-9cc2-0cdf5b01ba66.PNG)

**Comment by SeriousM** [comment]
same here. downloaded the editor and added the dependencies to it

**Comment by kubaizi** [comment]
any news guys on this issue ?

**Comment by kubaizi** [comment]
64

**Comment by zdenop** [comment]
Try this: https://github.com/zdenop/qt-box-editor/releases/tag/v1.12rc1
I do not use qt-box-editor for a long time and building it on windows it huge pain...

**Comment by binarydata** [comment]
> 
> 
> Try this: https://github.com/zdenop/qt-box-editor/releases/tag/v1.12rc1
> I do not use qt-box-editor for a long time and building it on windows it huge pain...

In regards to this as a fix, here's what happens when you run it.
![qt_box_error](https://user-images.githubusercontent.com/1411729/47392501-ad5f1a00-d6d1-11e8-86f0-528af85675ef.PNG)

**Comment by zdenop** [comment]
Did you install  `Microsoft Visual C++ 2017 Redistributable` package?

**Comment by binarydata** [comment]
![msft_redist](https://user-images.githubusercontent.com/1411729/47431145-108f9180-d750-11e8-9d2c-c9083092f302.PNG)
These are all the Microsoft Visual C++ packages I have installed.

**Comment by binarydata** [comment]
> 
> 
> Can you try [qt-box-editor-1.12rc1a-portable.zip](https://github.com/zdenop/qt-box-editor/files/2510607/qt-box-editor-1.12rc1a-portable.zip)? It works for me.

On my work laptop, it screams about the Qt Plugins not being found. On my personal laptop, I haven't tried. I've been super slammed at work, I'll have time to try it tonight/tomorrow.

**Comment by axltfytx** [comment]
![12rca](https://user-images.githubusercontent.com/43292251/47543551-5184d300-d915-11e8-9882-cf425833514e.JPG)

Windows 10
Qt5.11
 qt-box-editor-1.12rc1a-portable.zip 
It doesn't work

**Comment by zdenop** [comment]
I am sorry, I can not reproduce problem on my computer, so we need to play this game "download and try":
Here is another package [qt-box-editor-1.12rc1b-portable.zip]( https://github.com/zdenop/qt-box-editor/files/2529245/qt-box-editor-1.12rc1b-portable.zip) - please try it ;-)

**Comment by binarydata** [comment]
> I am sorry, I can not reproduce problem on my computer, so we need to play this game "download and try":
> Here is another package [qt-box-editor-1.12rc1b-portable.zip](https://github.com/zdenop/qt-box-editor/files/2529245/qt-box-editor-1.12rc1b-portable.zip) - please try it ;-)

Sorry for the late reply. I checked the dependencies and it all checks out. So I'm running Windows 10, not windows 8. However, I found v1.08, and it works. I'm going to try v1.09 and v1.10 when I get home. I'm not sure what's changed between v1.08 and v1.12 but for some reason, it does not like it.

**Comment by zdenop** [comment]
I am building and running it on Windows 10 with QT 5.11 and VS 2017...
Old version was build with mingw, but it is very difficult to build recent tesseract on windows with mingw

**Comment by binarydata** [comment]
I'll see if I can provide you with any more information. What build of Windows 10 are you on, and what do you have of VS 2017 installed?

I have everything on VS 2017 installed. I'm rocking the latest release of Windows 10. I'll see if I can't send a dxdiag over.

**Comment by zdenop** [comment]
I have:
- windows 10 64 bit version 1709, build 16299.547; 
- Qt 5.11.2
- Microsoft Visual Studio Community 2017  Version 15.8.5, but I  use QT Creator Community version 4.7.2 (that use VS for compilation)
- tesseract/leptonica were build with cppan build chain (VS 2017)

I still believe that there is just missing some lib, but I have problem to find computer without installed QT ;-)

**Comment by zdenop** [comment]
OK. Another try:
I [found out that QT has tool  windeployqt.exe](http://doc.qt.io/qt-5/windows-deployment.html#the-windows-deployment-tool) that should help to solve QT dependencies.
So I created new (64bit) package [qt-box-editor-1.12rc1c-portable.zip](https://github.com/zdenop/qt-box-editor/releases/download/v1.12rc1/qt-box-editor-1.12rc1c-portable.zip). I hope it will works now...
Please test it let me know results....

**Comment by binarydata** [comment]
![qt_box_1_12rc1](https://user-images.githubusercontent.com/1411729/50413697-ac2b9580-07c5-11e9-8d79-477591d75bad.PNG)

Works for me now. Though, I've gotta now figure out how to compile tesseract-ocr and some other stuff together.
