### ISSUE TITLE
How exactly do I "adjust location of leptonica and tesseract in qt-box-editor.pro"?

### ISSUE THREAD

**Issue by vmrodt** [zdenop/qt-box-editor#53]
How exactly do I "adjust location of leptonica and tesseract in qt-box-editor.pro"?
Do I need to do that too if I build it in Ubuntu?

**Comment by zdenop** [comment]
What error you get when you tried to build this program?

**Comment by vmrodt** [comment]
I get no errors (I used the instructions to build on Ubuntu) 
The problem is that when I open a png image I can't generate the boxes from the editor, the option "Generate boxes for page" does nothing (that's why I asked the question because I had imagined it might be related to this problem)
It is no longer a problem for me because I am now generating the boxes directly using tesseract. 
By the way the editor is very good and very helpful, thanks for it (It crashes sometimes, but if I save often it is not a problem)

**Comment by zdenop** [comment]
What version of tesseract are you using?

**Comment by vmrodt** [comment]
tesseract --version
tesseract 3.04.00
leptonica-1.72
libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8

**Comment by zdenop** [comment]
"Generate boxes for page" does not work is with tesseract 3.04 - there was change of tesseract API, that caused that this function stop to work. I will try to find solution, but it will not be soon...

**Comment by vmrodt** [comment]
Thank you, and again thank you for making the editor, it is very useful.

**Comment by mahadesarkar** [comment]
[tesseract --version
                   tesseract 3.04.00
                   leptonica-1.72]
     -->  Following the "building on ubuntu"  instructions -->after make comand , these showed-->
src/ChildWidget.cpp:28:34: fatal error: leptonica/allheaders.h: No such file or directory
compilation terminated.
Makefile:628: recipe for target 'temp/ChildWidget.o' failed
make: *** [temp/ChildWidget.o] Error 1
