### ISSUE TITLE
Ctrl + 1 shortcut "Join with Next Symbol" does not work.  It only works from the menu. 

### ISSUE THREAD

**Issue by vmrodt** [zdenop/qt-box-editor#54]
Ctrl + 1 shortcut "Join with Next Symbol" does not work.  It only works from the menu. 
(I am using version v1.12dev)

**Comment by zdenop** [comment]
What version of Qt are you using?

**Comment by vmrodt** [comment]
qmake --version
QMake version 3.0
Using Qt version 5.2.1 in /usr/lib/i386-linux-gnu

(I built it using the instructions for building on Ubuntu, I am using Ubuntu 14.04 LTS)

**Comment by zdenop** [comment]
I just test it with official Qt 5.5.1 (downloaded directly from http://www.qt.io/download) on openSUSE 13.2 64bit.
Shortcut ctrl+1 (also '1' from numpad ) works for me. I can set combination of keys, but Qt is responsible for handling shortcuts. So maybe there is problem with keyboard setting on Ubuntu and Qt... I am not able to do anything with it...
