### ISSUE TITLE
warning dialog on each save

### ISSUE THREAD

**Issue by acinader** [zdenop/qt-box-editor#57]
I build and am running head on a mac 10.11.5

Every time I save I get this warning dialog:

File '/Users/arthur/Desktop/tmp-84280Y19aDmZCDWaf.box' was modified outside of QT Box Editor.
Reload it?

I press no and am able to save.  Any idea what is going on?

**Comment by zdenop** [comment]
What Qt version are you using?

**Comment by acinader** [comment]
$ qmake --version
QMake version 2.01a
Using Qt version 4.8.7 in /usr/local/Cellar/qt/4.8.7_2/lib

**Comment by acinader** [comment]
trying brew uninstall qt; brew install qt5; brew link -f qt5

will keep you posted....

**Comment by acinader** [comment]
that works.  problem solved.
