### ISSUE TITLE
Tesseract 3.04 support

### ISSUE THREAD

**Issue by z3ntu** [zdenop/qt-box-editor#59]
That would be pretty nice!

**Comment by zdenop** [comment]
I rebuild qbe (git master branch) with tesseract master branch (a.k.a 3.05dev) and it works for me (I did not test it heavily ;-) ). What is exact problem?

**Comment by z3ntu** [comment]
Sorry, I don't know what I did back then. I'm gonna close this as I have no idea what I meant before. Maybe there was some warning that Tesseract 3.04 was not supported or something else.
