### ISSUE TITLE
drag right bbox border before left border

### ISSUE THREAD

**Issue by CDanU** [zdenop/qt-box-editor#60]
If one drags the right side of a bounding box before the left side I would expect that the right side becomes the left side.

Example:
0: l: **9**; b: 215; r: **117**; t: 16
1: drag & release
2: l: **_117_**; b: 215; r: **_9_**; t: 16

but it should be 

2: l: **9**; b: 215; r: **117**; t: 16

This leads to non clickable boxes in the qt-box-editor and most likely to other problems with tesseract.

HEAD at: a9e12776323df6b8bb74b95495ac1ce27f5cda76

E: The same problem also occurs with switched top and bottom sides

**Comment by zdenop** [comment]
Result is exactly what user made => it is correct. If it needs to be fixed it is user task to fix it.

**Comment by CDanU** [comment]
If one drags a bounding box, no matter how, one would always expect that the top left corner point is the top left corner point and not that it is internally for example a bottom right corner just because it was dragged so for convenience. Especially if there is no further visual indication for that.
The only reason to allow this behavior is if it enables other reasonable functionalities. If that is not the case this only leads to user errors.
