### ISSUE TITLE
Cannot install latest release, installation instructions unclear

### ISSUE THREAD

**Issue by incendor** [zdenop/qt-box-editor#62]
Hi,

I'm trying to get qt-box-editor to run but when trying to install it shows the following error:

`
In file included from src/ChildWidget.cpp:33:0:
src/TessTools.h:26:31: fatal error: tesseract/baseapi.h: No such file or directory
 #include <tesseract/baseapi.h>
                               ^
compilation terminated.
Makefile:645: recipe for target 'temp/ChildWidget.o' failed
make: *** [temp/ChildWidget.o] Error 1
`

I might be missing something since I'm not very familiar with linux systems but I can't seem to find out what's wrong.

Can someone help me?

**Comment by zdenop** [comment]
That error indicates that you do not have installed tesseract

**Comment by leo128** [comment]
Hello. I second incendor

I have tesseract installed from ubuntu repository and it works, but I still can't point to leptonica and tesseract libs.

"adjust location of leptonica and tesseract in qt-box-editor.pro" in install instructions is a bit vague, could you or anyone please provide some pointers? thank you

**Comment by zdenop** [comment]
Building app from source requires relevant knowledge. Your message indicate you does not have it ("I have tesseract installed from ubuntu repository and it works").  E.g. this is not issues of this project.
