### ISSUE TITLE
Build Instructions for Mac

### ISSUE THREAD

**Issue by IRobL** [zdenop/qt-box-editor#63]
It's kind of scary to run into a project that only has windows binaries especially when using a mac when you're more comfortable on linux.  I have these instructions to share and would take the time to create a PR w/ the author's approval, otherwise having them in the issue tracker should help folks out plenty:

### Steps
1.  Install the Apply published Xcode suite, and run at least once so the terms can be agreed to
2.  Install qt, and run the build setup
```
$  brew install qt
$  qmake
$  make
$  open qt-box-editor-1.13dev.app/
```

Great work on this project, btw!

**Comment by zdenop** [comment]
You are welcome to make PR ;-)
