### ISSUE TITLE
Make error with tesscallback.h

### ISSUE THREAD

**Issue by tonystark12** [zdenop/qt-box-editor#65]
First off, thank you for making this open source package, that has come in handy for many working with tesseract

I came across the following error while trying to make the qt-box-editor:

        /usr/local/include/tesseract/tesscallback.h:9701:20: error: ‘p1_’ was not declared in this scope
       (*function_)(p1_,p2_,p3_,p4_,p5_,p6_,a1,a2,a3,a4,a5);

and so on till 'p6_'. How can I resolve this?

My tesseract version and details:

        tesseract 4.00.00alpha
        leptonica-1.74.4
        libgif 4.1.6(?) : libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8 : libwebp 0.4.0

       Found SSE
Ubuntu version : 14.04

**Comment by zdenop** [comment]
This project was created for tesseract 3.02 .e.g. it should be compatible with 3.x version. Version 4.x is not supported - it has its own training process.
