### ISSUE TITLE
Tesseract couldn't load any languages!

### ISSUE THREAD

**Issue by vitiennam** [zdenop/qt-box-editor#72]
Hi all,

I install qt box and do not know how to config to tessdata
Please help me

Log:
Failed loading language 'eng'
Tesseract couldn't load any languages!
![image](https://user-images.githubusercontent.com/20283416/44025870-7ce3b5c2-9f1b-11e8-8e68-68a1eb1f69ba.png)

Thanks

**Comment by zdenop** [comment]
If you see "English" in language field (or any other language), than your configuration is correct.

**Comment by kimchicanh** [comment]
@zdenop But it have problem:
Failed loading language 'eng'
Tesseract couldn't load any languages!

why does it fail ???

Thanks

**Comment by zdenop** [comment]
where/when you have this error?

Dňa ut 14. 8. 2018, 3:27 kimchicanh <notifications@github.com> napísal(a):
