### ISSUE TITLE
Run QtBox after build from source via make command line

### ISSUE THREAD

**Issue by tonquangtu** [zdenop/qt-box-editor#75]
Hi.

I'm trying build qt-box from source for ubuntu.
I following INSTALL file in folder when I downloaded source code from github.

After I run command line 'make with no error. I run this command line for install: sudo install make

But I get an error is: 'make: Nothing to be done for 'install'.'

How can I install after make ?

**Comment by zdenop** [comment]
there is no install - just us it or copy wherever you want.

**Comment by AhmadAlhati** [comment]
having the same problem
sorry, but i didnt get that ..
i can not launch the app window ?!

**Comment by zdenop** [comment]
I you build it successfully there is executable. What is difficult to run executable?

**Comment by AhmadAlhati** [comment]
the only executable app after build, is (Qt assistant)
i followed the installation command, but nothing happened

BUILDING ON UBUNTU
==================

sudo apt-get install qt5-qmake
sudo apt-get install qt5-default
sudo apt-get install libqt5gui5
sudo apt-get install qt5-doc
sudo apt-get install libqt5svg5-dev
sudo apt-get install libleptonica-dev

qmake -qt=5
make

**Comment by zdenop** [comment]
Are you familiar with building from source? What is output of make?

**Comment by AhmadAlhati** [comment]
not really,
the output:: make: Nothing to be done for 'first'.

**Comment by zdenop** [comment]
So you did not compile it (probably problem with configuration) ;-).
I am sorry but this is not issue of this project - it is more about your knowledge. 
Also it is question if this is still relevant project, because it was useful at the time of tesseract 3.x, but know with tesseract 4 it does not help you.
