### ISSUE TITLE
qt-box-editor-1.11  Click nothing

### ISSUE THREAD

**Issue by tohn21** [zdenop/qt-box-editor#79]
copy there qt-box-editor-1.11.exe
extract there qt-box-editor-dependecies-1.11.zip
1.09 works, but 1.11 doesn't work, and 1.11 has no error message.
Is there something wrong with my environment?Win10 1903
![Snipaste_2019-11-09_23-46-12](https://user-images.githubusercontent.com/20418857/68531225-3384e780-034b-11ea-864e-9f5d256ee278.png)

**Comment by zdenop** [comment]
why you did not try [the latest version](https://github.com/zdenop/qt-box-editor/releases/tag/v1.12rc1)?

**Comment by tohn21** [comment]
> 为什么您没有尝试[最新版本](https://github.com/zdenop/qt-box-editor/releases/tag/v1.12rc1)？

Thank you very much for your reply!I use this version because I need to be compatible with win7, win8, win10 and xp, so I can only use the lower version.

**Comment by zdenop** [comment]
Than you are in trouble - without error message there is no possibility to find solution...
If any investigation would start (e.g. adding some debugging info) it would be in 1.12 version... Anyway AFAIK all systems you mentioned excluding win10 are officially unsupported by MS, so...

**Comment by tohn21** [comment]
Thank you for your reply. I will think of other ways to solve this problem. Thank you!
