### ISSUE TITLE
All the training boxes are 90 degrees off

### ISSUE THREAD

**Issue by cybernard** [zdenop/qt-box-editor#84]
So I used tesseract make.box with a newer version of tesseract, I believe version 5?

Then I loaded the box data, and all the boxes seem to be rotated to the left 90 degrees.
Therefore none of the boxes lined up with the text on the screen.

**Comment by zdenop** [comment]
QTB is designed for tesseract 3x training. So it is ok if it fails with the newer version which changed the training process.
