### ISSUE TITLE
Github pages 404 error

### ISSUE THREAD

**Issue by amitdo** [zdenop/qt-box-editor#85]
Hi Zdenko,

The link in this project front page should be changed from:
https://zdenop.github.com/qt-box-editor
to:
https://zdenop.github.io/qt-box-editor

**Comment by zdenop** [comment]
but I add also reference to [zdenop.github.io/qt-box-editor](https://zdenop.github.io/qt-box-editor)

**Comment by amitdo** [comment]
I was referring to another link, on top part, before the README starts.

**Comment by zdenop** [comment]
And it is fixed - right?

**Comment by amitdo** [comment]
![Screenshot from 2022-06-20 11-34-22](https://user-images.githubusercontent.com/13571208/174561394-d80b9fce-88a8-45c9-bcfa-84838e711c33.png)

**Comment by zdenop** [comment]
thanks. changed.
