### ISSUE TITLE
Build failure with leptonica 1.83

### ISSUE THREAD

**Issue by risicle** [zdenop/qt-box-editor#87]
Leptonica 1.83 moved a number of `struct` definitions into "private" headers, notably `Pix` and `Box` et al.

This causes a build failure:

```
src/TessTools.cpp:147:25: error: member access into incomplete type 'PIX' (aka 'Pix')
   l_uint32 *datas = pixs->data;
...
```

To address this, an extra import of `<leptonica/pix_internal.h>` needs to be added to `src/TessTools.h`.

On top of this, it looks like this version got rid of the library's `lept` alias, so references to `-llept` in `qt-box-editor.pro` need to be switched to `-lleptonica`.

**Comment by zdenop** [comment]
qt-box-editor was IMO relevant for tesseract 3.x training (legacy engine) and it does not provide any value for the current tesseract version... 
So what is the value if it is possible to build with the latest version of leptonica&tesseract?

**Comment by zdenop** [comment]
It is not problem to include patch here, I just wander if really people are actively using this.

**Comment by zdenop** [comment]
LSTM engine does not need to be trained from scratch (legacy engine has to). E.g. you can train and extend only problems.
IMO LSTM training is (could be) faster as you do not need to take care about bounding boxes of letters and training based on tutorials like [this](https://bucket401.blogspot.com/2023/01/tesseract-lstm-training-aka-makefile.html) seem to be pretty easy.

Anyway I made [requested changes of QTB code](https://github.com/zdenop/qt-box-editor/commit/db59855a6d82ef559ab1dd4e4496643a8c3a0503).

**Comment by zdenop** [comment]
fixed.
