### ISSUE TITLE
SPACE Character Automatically Replaced to Empty character  When Saving

### ISSUE THREAD

**Issue by thucnv6688** [zdenop/qt-box-editor#88]
When editing a .box file containing SPACE characters (U+0020) using QT Box Editor, the SPACE characters are automatically removed (or replaced with an empty character) after saving the file. This behavior is similar to applying a String.Trim() function, which unintentionally removes the whitespace characters from the .box file.

Steps to Reproduce:
Open a .PNG file in QT Box Editor that contains SPACE characters (U+0020).
Edit any character in the file (e.g., modify its bounding box or glyph).
Save the file using the Save button.
Check the resulting .box file:
All SPACE characters are no longer present in the file.

**Comment by thucnv6688** [comment]
![before](https://github.com/user-attachments/assets/f5522014-47a7-48af-9fe6-6376f91cb1d2)
![after](https://github.com/user-attachments/assets/6fff8efb-c136-4434-bf77-23f99ac72c30)

**Comment by zdenop** [comment]
That is correct and expected behavior.

**Comment by thucnv6688** [comment]
If so, it will cause an error in my .box file. I won’t be able to train the Space character.

Is there a way to keep the SPACE character intact the first time I open the .box file?

**Comment by zdenop** [comment]
Can you elaborate on "tesseract can train space character"?

**Comment by thucnv6688** [comment]
Yes. I am using Tesseract v5.4.0.

Here are my steps:

Step 1:
- I have invoices in .png image format.
- I use jTessBoxEditor to create .box files corresponding to each image file.
- In jTessBoxEditor, I use the "Make LSTM Box File" function.
- The generated .box file contains the SPACE character (I have attached the file).

Step 2:
- I use QT Box Editor to edit the .box file because QT Box Editor is very convenient for editing .box files.
- QT Box Editor allows dragging and resizing boxes quickly.
- However, I encounter an issue where SPACE characters are automatically deleted when I open the .box file for the first time.
- Then, in QT Box Editor, I manually re-enter the SPACE character in the correct positions where it was removed.

Step 3:
-I use TessTrain for training.

![Screenshot_1](https://github.com/user-attachments/assets/60a8aaa8-18f3-4589-b75e-cad9dad43153)
![Screenshot_2](https://github.com/user-attachments/assets/06743ee1-6517-436b-b140-b01e7763c57e)
![Screenshot_3](https://github.com/user-attachments/assets/91f9af81-35e9-4b78-b72f-a7191bc4a70b)
![Screenshot_4](https://github.com/user-attachments/assets/1e41203e-2123-48c7-bd2f-aa213db0c5d2)
![Screenshot_5](https://github.com/user-attachments/assets/d021847c-70d3-42f7-9e67-dd60db7a87ba)
![Screenshot_6](https://github.com/user-attachments/assets/4100b8db-6829-42be-8385-9bd42a7de6d3)

**Comment by zdenop** [comment]
And from where do you have idea that tesseract train spaces???

**Comment by thucnv6688** [comment]
I am new to Tesseract OCR.

I noticed that when I do not use the SPACE character, the result shows text that is stuck together, without separating the FULL NAME properly.

Could you please explain this further? I noticed that jTessBoxEditor also generates SPACE characters when creating the .box file.

**Comment by zdenop** [comment]
If you are new to tesseract DO NOT TRAIN it! You waste your time and time of others.
